# ------------ Workload ------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  selector:
    matchLabels:
      app: broker
  replicas: 1
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: abyanmajid/yan-broker:0.1.0

---
# ------------ Service ------------
apiVersion: v1
kind: Service
metadata:
  name: broker

spec:
  selector:
    app: broker

  ports:
    - name: http
      port: 8080
      nodePort: 30080

  type: NodePort
