# ------------ Broker Deployment ------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  selector:
    matchLabels:
      app: broker
  replicas: 1
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: localhost:5000/broker
          ports:
            - containerPort: 8080
          env:
            - name: API_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: API_TOKEN

---
# ------------ Broker Service ------------
apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  selector:
    app: broker
  ports:
    - name: http
      port: 8080
      nodePort: 30080
  type: NodePort
