# ------------ CMS Deployment ------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
spec:
  selector:
    matchLabels:
      app: cms
  replicas: 1
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
        - name: cms
          image: localhost:5000/cms
          env:
            - name: YAN_CMS_DB_URI
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: YAN_CMS_DB_URI
          ports:
            - containerPort: 8000
---
# ------------ CMS Service ------------
apiVersion: v1
kind: Service
metadata:
  name: cms
spec:
  selector:
    app: cms
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
