# ------------ Workload ------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
spec:
  selector:
    matchLabels:
      app: cms
  replicas: 1
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
        - name: cms
          image: abyanmajid/yan-cms:0.1.0

---
# ------------ Service ------------
apiVersion: v1
kind: Service
metadata:
  name: cms

spec:
  selector:
    app: cms

  ports:
    - name: http
      port: 8080

  type: ClusterIP
